### PR TITLE
Add a configuration to override the URL validation.

### LINKED ISSUE #37: Override the validation url
Hello, 
Using phpCAS is possible to override the validation URL but not with XavRsl/Cas.
Example: 
https://github.com/Jasig/phpCAS/blob/master/docs/examples/example_custom_urls.php#L39
```
// Override the validation url for any (ST and PT) CAS 2.0 validation
phpCAS::setServerProxyValidateURL('https://cas.example.org:1443/proxyValidate');
// Override the validation url for any CAS 1.0 validation
//phpCAS::setServerServiceValidateURL('https://cas.example.org:1443/serviceValidate');
//Override the validation url for any SAML11 validation
//phpCAS::setServerSamlValidateURL('https://cas.example.org:1443/samlValidate');
```

I really need this option to retrieve custom attributes for the logged user, so I will submit a patch for this.

### PR DESCRIPTION
**Pull request by erozqba**
Fix #37 
---------

Changes:
* Add an optional configuration to set a custom URL validation.

### CODE REVIEW

**Comment by XavRsl** [comment]
Hi Ernesto,
Thank you for the time you spent on your pull request. 
A few things bother me in your commit. You are using phpCAS::setServerServiceValidateURL but this method is only used in CAS 1.0 validation (https://developer.jasig.org/cas-clients/php/1.1.3/docs/api/group__publicAuth.html#gaddd5fc35d30270c1230c334730da0b17). Your code validates the URL when using SAML but not in proxy mode when there is a method for that https://developer.jasig.org/cas-clients/php/1.1.3/docs/api/group__publicAuth.html#gafeda1ee79b77d0ce1d6d2d0be92851d4.
Finally, could you rewrite your comments for configureServerValidateURL method and for Custom CAS Validation URL config, they don't provide any helpful information.

Thanks,

Xavier

**Comment by erozqba** [comment]
Hi XavRsl,
Thanks for your quick feedback, I will try to make the changes that you propose and open another PR.
I have some question and maybe you can help me to find the answers or a preferable way to find out a solution: 

* Right now, the version of CAS is hard coded in `Sso::configureCasClient` to `CAS_VERSION_2_0 `or `SAML_VERSION_1_1`, so is not possible to use CAS 1.0 and then use  `phpCAS::setServerServiceValidateURL`.
* In the project I'm working right now the authentication works fine with `CAS_VERSION_2_0` but I have to use `phpCAS::setServerServiceValidateURL` to find out the user attributes, because if I use `phpCAS::setServerProxyValidateURL` an empty array is returned for the attributes. 

I will appreciate any suggestion, to make this work for everyone and the `phpCAS::setServerServiceValidateURL` can be used even when the CAS version is 2.0 ?

**Comment by XavRsl** [comment]
To be honest I don't know. I'm simply relying on the Cas API docs but never used this method. You should ask your questions on the PhpCAS github page, they should provide you better answers. 

--
Xavier

**Comment by erozqba** [comment]
There is a reason why you only use `CAS_VERSION_2_0` or `SAML_VERSION_1_1` and there are not the possibility to use CAS version 1.0?

**Pull request closed without merging**
